CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK name <>'',
    lastName TEXT NOT NULL CHECK lastName <>'',
    email text NOT NULL 
    password text NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    amount integer,
    category text,
    userId integer REFERENCES users(id)
);